### ISSUE TITLE
Test build/tear down Staging/Production environments

### ISSUE THREAD

**Issue by TomJKing** [nationalarchives/tdr-terraform-environments#19]

**Comment by TomJKing** [comment]
Built and tore down staging and production environments separately.

Issue with running the environments on the same account together as hit the limit of the number of allowed Elastic IP address per account. Each individual environment requires four, but the current account limit is 5 per account. See https://docs.aws.amazon.com/vpc/latest/userguide/amazon-vpc-limits.html

Options are:
- ask AWS for an increase
- create a new AWS account and host a single TDR environment per AWS account

Requires achitectural input.

**Comment by suzannehamilton** [comment]
What are we using the four elastic IPs for?

**Comment by TomJKing** [comment]
Asked David Clipsham to ask AWS about increasing the limit of Elastic IPs

**Comment by suzannehamilton** [comment]
This card is now blocked until we've created a separate AWS account for production, which will also solve the Elastic IP limit.

**Comment by paulschwarzenberger** [comment]
unblocked as we now have separate staging and production AWS accounts

**Comment by suzannehamilton** [comment]
Closing this issue because we've switched to Jira.
